### PR TITLE
Testing ht functions - Dependent on PR #6!!

### PR DESCRIPTION
**Pull request by aaswenson**
Fix deprecated tests. Added two more to test oned_flow_modeling

1. test_flow_calc() - tests against [this](https://drive.google.com/open?id=1iGJPpuZygWxE2-stEh6cS0AVwugiRgB_HJcaW2gzhhI) hand calculation
2. test_rand_flow_calc() - uses random values to perform the oned_flow_modeling calculation, then verifies the result manually using the Flow class

### CODE REVIEW

**Comment by gonuke** [comment]
Can you rebase this?  The commit history looks a little "wonky" and I think that's why it shows repeated changes from the switch to radius.....

**Comment by gonuke** [comment]
Is this ready for review?

**Comment by aaswenson** [comment]
@gonuke It's ready. Circleci seems to be working.

**Comment by gonuke** [comment]
Nice to have some tests... good work @aaswenson

**Pull request merged**
